pr: none
trigger: none

resources:
  webhooks:
    - webhook: kubeflowyo-kv          
      connection: kubeflowyo-kv

steps:
  - task: Bash@3
    name: "test"
    displayName: "Testing"
    inputs:
      targetType: 'inline'
      script: |
        echo ${{ parameters.kubeflowyo-kv.data.validationCode }}
        echo ${{ parameters.kubeflowyo-kv.data.validationUrl }}
        echo "yay"

