pr: none
trigger: none

resources:
  webhooks:
    - webhook: kubeflowyokv2
      connection: kubeflowyokv2

steps:
  - task: Bash@3
    name: "test"
    displayName: "Testing"
    inputs:
      targetType: 'inline'
      script: |
        # echo ${{ parameters.kubeflowyokv2.data.validationCode }}
        # echo ${{ parameters.kubeflowyokv2.data.validationUrl }}
        echo "yay"

