pr: none
trigger: none

resources:
  webhooks:
    - webhook: kubeflowyokv
      connection: kubeflowyokv

steps:
  - task: Bash@3
    name: "test"
    displayName: "Testing"
    inputs:
      targetType: 'inline'
      script: |
        echo ${{ parameters.kubeflowyokv.data.validationCode }}
        echo ${{ parameters.kubeflowyokv.data.validationUrl }}
        echo "yay"

