# Pipeline to run basic code quality tests as part of pull requests to the master branch.

resources:
  containers:
    - container: mlops
      image: mcr.microsoft.com/mlops/python:latest

trigger: none
pr:
  branches:
    include:
      - master

pool:
  vmImage: "ubuntu-latest"

container: mlops

steps:
  - template: code-quality-template.yml
  - task: Bash@3
    name: "compile_pipeline"
    displayName: "Compile Pipeline"
    inputs:
      targetType: 'inline'
      script: |
        pip install kfp --upgrade --user
        python code/pipelineazdo.py
