apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"                # [OPTIONAL] if not provided, will default to "false"
    userAssignedIdentityID: $AZ_CLIENT_ID  # Service Principal appid
    keyvaultName: $AZ_KEYVAULT             # the name of the KeyVault
    cloudName: ""                          # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: "azdopat"
          objectType: secret               # object types: secret, key or cert
          objectVersion: ""                # [OPTIONAL] object versions, default to latest if empty
    resourceGroup: $AZ_RESOURCE_GROUP      # the resource group of the KeyVault
    subscriptionId: $AZ_SUBSCRIPTION_ID    # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: $AZ_TENANT_ID                # the tenant ID of the KeyVault  