apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csr-approver
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - update
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  resourceNames:
  - kubernetes.io/*
  verbs:
  - approve
  
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
 name: csr-approver-binding
subjects:
- kind: ServiceAccount
  name: kubeflow-pipelines-cache-deployer-sa
  namespace: kubeflow
roleRef:
 kind: ClusterRole
 name: csr-approver
 apiGroup: ""
