name: CD
on:
  repository_dispatch:
    types: [Model is registered]
    
jobs:
  deploy_to_qa:
    runs-on: ubuntu-latest

    
    # TODO: refactor into two jobs
    #       build image and deploy the inference
    steps:    
    - name: Copy Repository Contents
      uses: actions/checkout@master

    - name: Install Python dependencies
      run: |
        pip3 install requests --upgrade


    - name: Handle Deploy Event
      id: deh
      run: |
        python3 event_dispatcher.py --event_type "deploy"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: .github/events

    - name: Download model
      run: |
        cd $GITHUB_WORKSPACE/code/seldon        
        mlflow_run_id=$(curl -d '{"experiment_ids":['$MLFLOW_EXPERIMENT'],"filter":"tags.external_run_id='\'''$RUN_ID''\''"}' ${{ secrets.KFP_DSHB }}/mlflow/api/2.0/preview/mlflow/runs/search | jq -r '.runs[0].info.run_id')     
        curl -L '${{ secrets.KFP_DSHB }}/mlflow/get-artifact?path=model/data/model.h5&run_uuid='$mlflow_run_id > model.h5    
      env:
        RUN_ID: ${{ steps.deh.outputs.RUN_ID }}   
        MLFLOW_EXPERIMENT: ${{ secrets.MLFLOW_EXPERIMENT }}       


    - name: Build Scoring image
      run: |
        cd $GITHUB_WORKSPACE/code/seldon
        ls -ltr
        echo ${{ secrets.DOCKER_PWD}} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
        docker build $GITHUB_WORKSPACE/code/seldon -t ${{ secrets.MODEL_IMAGE_NAME }}:$RUN_ID
        docker push ${{ secrets.MODEL_IMAGE_NAME }}:$RUN_ID
      env:
        RUN_ID: ${{ steps.deh.outputs.RUN_ID }}  
        

    
    - name: Deploy Model to SeldonCore
      uses: WyriHaximus/github-action-helm3@master
      with:      
        exec: helm upgrade ${{ secrets.DEPLOYMENT_NAME }} $GITHUB_WORKSPACE/code/seldon/chart --install --set=image.tag=$RUN_ID
        kubeconfig: ${{ secrets.KUBECONFIG }}        
      env:
        RUN_ID: ${{ steps.deh.outputs.RUN_ID }}        

  deploy_to_uat:
    runs-on: ubuntu-latest
    needs: deploy_to_qa
    if: false
    
    steps:    
    - name: Copy Repository Contents
      uses: actions/checkout@master

    
    - name: Deploy Model to KFServing
      uses: WyriHaximus/github-action-helm3@master
      with:      
        exec: helm upgrade ${{ secrets.DEPLOYMENT_NAME }} $GITHUB_WORKSPACE/code/kfserving/custom/chart --install --set=image.tag=$RUN_ID
        kubeconfig: ${{ secrets.KUBECONFIG }}        
      env:
        RUN_ID: ${{ steps.deh.outputs.RUN_ID }}        

  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: deploy_to_uat

    steps:    
    - name: Copy Repository Contents
      uses: actions/checkout@master

    - name: Install Python dependencies
      run: |
        pip3 install requests --upgrade

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.SERVICE_PRINCIPAL }}", "clientSecret":"${{ secrets.SERVICE_PRINCIPAL_PWD }}", "subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}", "tenantId":"${{ secrets.TENANT }}"}' 
    - name: Deploy
      uses: azure/CLI@v1
      with:
        inlineScript: |          
          cd $GITHUB_WORKSPACE/code/deploy
          ./deploy.sh -m ${{ secrets.MODEL_NAME }} \
                      -u ${{ secrets.SUBSCRIPTION_ID }} \
                      -r ${{ secrets.RESOURCE_GROUP }} \
                      -w ${{ secrets.AML_WORKSPACE }} \
                      -x ${{ steps.deh.outputs.RUN_ID }} \
                      -d ${{ secrets.DEPLOYMENT_NAME }}


      
